#!/usr/bin/env bash

flashDir="/mnt/research/SNAPhU/zac/BANG"
eosDir="/mnt/research/SNAPhU/zac/tables"

# argument is a simulation directory name
if [ $# -eq 0 ]; then
    read -p "please enter a model_set name: " model_set
    read -p "please enter a model name: " simulationDirName
else
    if [ $# -eq 2 ]; then
	model_set=$1
        simulationDirName=$2
    else
        echo "setupCCSN takes two arguments: model_set, model"
        exit 0
    fi
fi

# check if the simulation dir exists
simPath=${flashDir}/runs/${model_set}/${simulationDirName}

if [ -d "${simPath}" ]; then 
    echo "The simulation directory '${simPath}' already exists"
    read -p "Do you want to continue (y/n)? " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# check the EoS folder
if [ ! -d "$eosDir" ] || [ ! "$(ls -A $eosDir)" ]; then 
    echo "The given EoS folder does not exist or is empty."
    exit 1
fi

# setup simulation folder
srcDir="${flashDir}/obj/obj_${simulationDirName}"
mkdir ${simPath}

cd ${flashDir}
cp flash_helmnet.par ${simPath}/flash.par
#cp sbatch_run.sh ${simPath}/

cd ${simPath}
mkdir output

# link files for simulation
ln -sf "${srcDir}/flash4"
ln -sf "${srcDir}/helm_table.dat"
ln -sf "${srcDir}/SpeciesList.txt"
ln -sf "${srcDir}/winvne_v2.0.dat"
ln -sf ${eosDir} EoSTables
ln -sf "${flashDir}/source/Simulation/SimulationMain/CoreCollapse/progenitors"

echo "Simulation is ready!"
