#!/usr/bin/env bash

./setup CoreBurn -auto -1d +spherical -objdir obj/coreburn_0 -nxb=12 --with-unit=physics/sourceTerms/Burn/BurnMain/nuclearBurn/Aprox21 +newMpole threadWithinBlock=False +spark --site=dev-intel16 -makefile=gnu
